version: "3.8"
services:
  redis:
    container_name: redis
    image: redis:4
    command: redis-server --requirepass admin
    volumes:
      - redis:/data
    ports:
      - 6379:6379
    networks:
      - bubble

networks:
  bubble:
    external: true

volumes:
  redis: